spring:
  application:
    name: service-etcr
  datasource:
    url: jdbc:mysql://localhost:3306/lightingdetection?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 61000
#ribbon的超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8081/eureka/
server:
  port: 8084
security:
  user:
    name: test
    password: test
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  #pattern:
  #格式化，只能输出日期和内容
  #console: "%d - %msg%n"
  path: /usr/logs
  file: /usr/logs/etcr.log
