spring:
  application:
    name: service-total
  datasource:
    url: jdbc:mysql://localhost:3306/lightingdetection?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8081/eureka/
server:
  port: 8092
security:
  user:
    name: test
    password: test
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  #pattern:
  #格式化，只能输出日期和内容
  #console: "%d - %msg%n"
  path: /usr/logs
  file: /usr/logs/total.log
